#language:
#   - latex

before_install:
   - "sudo apt-get update && sudo apt-get install -y texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended"

script:
    make

after_success:
    coveralls;

notifications:
  email: false
